# Parameters for the gripper v4l2_camera_node.
/**:
  ros__parameters:
    # Use /dev/video2 (typically the second physical USB camera)
    video_device: "/dev/video2"
    pixel_format: "YUYV"
    output_encoding: "rgb8"
    image_size: [640, 480]
    # Gripper cam can also run at 5 fps to save bandwidth
    time_per_frame: [1, 5]
    camera_frame_id: "gripper_camera_link"
