# Parameters for the gripper v4l2_camera_node.
/**:
  ros__parameters:
    video_device: "/dev/v4l/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-video-index0"
    pixel_format: "YUYV"
    output_encoding: "rgb8"
    image_size: [640, 480]
    time_per_frame: [1, 5]
    camera_frame_id: "gripper_camera_link"
